name: golangci-lint
on:
  push:
    tags:
    - v*
    branches:
    - master
    - main
  pull_request:
    branches:
      - main
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: --timeout=2m
        version: latest
